/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type Metric = {
  _type: "metric";
  value: string;
  label: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PdfDocument = {
  _type: "pdfDocument";
  title: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  pages: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Persona = {
  _type: "persona";
  name: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  traits?: Array<string>;
  opportunitiesLead?: string;
  opportunities?: Array<string>;
  barriers?: Array<string>;
};

export type GalleryScreen = {
  _type: "galleryScreen";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  fullPage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role: string;
  organization: string;
  start: string;
  end?: string;
  location?: string;
  highlights?: Array<string>;
  caseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  intro?: string;
  image?: ImageWithAlt;
  body?: RichText;
  cta?: Link;
  seoDescription?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type CreativeWork = {
  _id: string;
  _type: "creativeWork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  kind:
    | "designSystem"
    | "strategy"
    | "audit"
    | "data"
    | "ux"
    | "brand"
    | "logo"
    | "campaign"
    | "printAd"
    | "graphic"
    | "illustration"
    | "cover"
    | "book";
  image?: ImageWithAlt;
  cardFit?: "fill" | "whole";
  client?: string;
  year?: string;
  credit?: string;
  summary?: string;
  gallery?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  documents?: Array<
    {
      _key: string;
    } & PdfDocument
  >;
  documentsHeading?: string;
  howItStarted?: RichText;
  body?: RichText;
  caseStudy?: CaseStudyReference;
  externalUrl?: string;
  mature?: boolean;
  featured?: boolean;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type CreativeWorkReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "creativeWork";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  siteDescription?: string;
  ownerName?: string;
  headerLogo?: ImageWithAlt;
  gridNav?: Array<{
    label: string;
    href: string;
    cell: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
    _type: "gridCell";
    _key: string;
  }>;
  contactEmail?: string;
  linkedinUrl?: string;
  footerLine?: string;
  heroBrandmark?: ImageWithAlt;
  heroVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  heroPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quickActions?: Array<{
    label: string;
    href: string;
    icon?: "resume" | "work" | "about" | "contact" | "creative" | "hire";
    _type: "quickAction";
    _key: string;
  }>;
  headline?: string;
  intro?: string;
  primaryCta?: Link;
  secondaryCta?: Link;
  proofStats?: Array<
    {
      _key: string;
    } & Metric
  >;
  featuredHeading?: string;
  featuredCaseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  creativeTeaser?: {
    heading?: string;
    body?: string;
    cta?: Link;
  };
  clientTeaser?: {
    heading?: string;
    body?: string;
    cta?: Link;
  };
  workTitle?: string;
  workIntro?: string;
  workEmpty?: string;
  caseStudyGroups?: Array<{
    heading: string;
    studies: Array<
      {
        _key: string;
      } & CaseStudyReference
    >;
    _type: "caseStudyGroup";
    _key: string;
  }>;
  caseStudiesMoreHeading?: string;
  fullPageLabel?: string;
  howItStartedHeading?: string;
  documentsHeading?: string;
  personasHeading?: string;
  opportunitiesLabel?: string;
  barriersLabel?: string;
  enlargeLabel?: string;
  closeLabel?: string;
  previousLabel?: string;
  nextLabel?: string;
  pdfBadge?: string;
  pdfPageCounter?: string;
  pdfDownloadLabel?: string;
  fullscreenLabel?: string;
  exitFullscreenLabel?: string;
  creativeTitle?: string;
  creativeIntro?: string;
  portfolioSections?: {
    ux?: {
      title?: string;
      intro?: string;
    };
    brand?: {
      title?: string;
      intro?: string;
    };
    design?: {
      title?: string;
      intro?: string;
    };
    illustration?: {
      title?: string;
      intro?: string;
    };
  };
  portfolioViewAll?: string;
  creativeSections?: {
    data?: string;
    audit?: string;
    strategy?: string;
    designSystem?: string;
    ux?: string;
    brand?: string;
    illustration?: string;
    cover?: string;
    book?: string;
    campaign?: string;
    printAd?: string;
    graphic?: string;
    logo?: string;
  };
  kindLabels?: {
    data?: string;
    audit?: string;
    strategy?: string;
    designSystem?: string;
    ux?: string;
    brand?: string;
    logo?: string;
    campaign?: string;
    printAd?: string;
    graphic?: string;
    illustration?: string;
    cover?: string;
    book?: string;
  };
  uxCaseStudies?: Array<
    {
      _key: string;
    } & CaseStudyReference
  >;
  portfolioUxCaseStudy?: CaseStudyReference;
  portfolioUxPieces?: Array<
    {
      _key: string;
    } & CreativeWorkReference
  >;
  caseStudiesRowHeading?: string;
  caseStudyLabel?: string;
  matureLabel?: string;
  resumeTitle?: string;
  resumeIntro?: string;
  resumePdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  resumeDownloadLabel?: string;
  experienceHeading?: string;
  skillsHeading?: string;
  skillGroups?: Array<{
    heading: string;
    skills?: Array<string>;
    _type: "skillGroup";
    _key: string;
  }>;
  educationHeading?: string;
  education?: Array<string>;
  contactTitle?: string;
  contactIntro?: string;
  inquiryTypes?: Array<{
    label: string;
    description?: string;
    subject: string;
    _type: "inquiryType";
    _key: string;
  }>;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  organization?: string;
  role?: string;
  years?: string;
  skills?: Array<string>;
  heroImage?: ImageWithAlt;
  heroBackground?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  metrics?: Array<
    {
      _key: string;
    } & Metric
  >;
  body?: RichText;
  personasIntro?: string;
  personas?: Array<
    {
      _key: string;
    } & Persona
  >;
  galleries?: Array<{
    heading: string;
    intro?: string;
    placement?: "before" | "after";
    layout?: "phone" | "wide";
    images?: Array<
      | ({
          _key: string;
        } & ImageWithAlt)
      | ({
          _key: string;
        } & GalleryScreen)
    >;
    _type: "gallery";
    _key: string;
  }>;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  order?: number;
  seoDescription?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | RichText
  | Link
  | Metric
  | SanityFileAssetReference
  | SanityImageAssetReference
  | PdfDocument
  | Persona
  | GalleryScreen
  | ImageWithAlt
  | CaseStudyReference
  | Experience
  | Page
  | Slug
  | CreativeWork
  | SanityImageCrop
  | SanityImageHotspot
  | CreativeWorkReference
  | SiteSettings
  | CaseStudy
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type=="siteSettings" && _id=="siteSettings"][0]{  ...,  "resumePdfUrl": resumePdf.asset->url,  "heroVideoUrl": heroVideo.asset->url,  "headerLogoSize": headerLogo.asset->metadata.dimensions{width,height},  "heroVideoType": heroVideo.asset->mimeType,  "featuredCaseStudies": featuredCaseStudies[defined(@->slug.current)]->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics},  "uxCaseStudies": uxCaseStudies[defined(@->slug.current)]->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics},  "caseStudyGroups": caseStudyGroups[]{_key,heading,"studies": studies[defined(@->slug.current)]->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics}},  "portfolioUxCaseStudy": portfolioUxCaseStudy->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics},  "portfolioUxPieces": portfolioUxPieces[defined(@->slug.current)]->{_id,title,"slug":slug.current,kind,image,cardFit,"opaque": image.asset->metadata.isOpaque,gallery,client,year,credit,summary,externalUrl,mature,featured,  "hasPage": count(body) > 0 || count(documents) > 0,  "caseStudySlug": caseStudy->slug.current}}
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  siteDescription?: string;
  ownerName?: string;
  headerLogo?: ImageWithAlt;
  gridNav?: Array<{
    label: string;
    href: string;
    cell: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
    _type: "gridCell";
    _key: string;
  }>;
  contactEmail?: string;
  linkedinUrl?: string;
  footerLine?: string;
  heroBrandmark?: ImageWithAlt;
  heroVideo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  heroPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quickActions?: Array<{
    label: string;
    href: string;
    icon?: "about" | "contact" | "creative" | "hire" | "resume" | "work";
    _type: "quickAction";
    _key: string;
  }>;
  headline?: string;
  intro?: string;
  primaryCta?: Link;
  secondaryCta?: Link;
  proofStats?: Array<
    {
      _key: string;
    } & Metric
  >;
  featuredHeading?: string;
  featuredCaseStudies: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    organization: string | null;
    role: string | null;
    years: string | null;
    skills: Array<string> | null;
    heroImage: ImageWithAlt | null;
    metrics: Array<
      {
        _key: string;
      } & Metric
    > | null;
  }> | null;
  creativeTeaser?: {
    heading?: string;
    body?: string;
    cta?: Link;
  };
  clientTeaser?: {
    heading?: string;
    body?: string;
    cta?: Link;
  };
  workTitle?: string;
  workIntro?: string;
  workEmpty?: string;
  caseStudyGroups: Array<{
    _key: string;
    heading: string;
    studies: Array<{
      _id: string;
      title: string;
      slug: string;
      summary: string;
      organization: string | null;
      role: string | null;
      years: string | null;
      skills: Array<string> | null;
      heroImage: ImageWithAlt | null;
      metrics: Array<
        {
          _key: string;
        } & Metric
      > | null;
    }>;
  }> | null;
  caseStudiesMoreHeading?: string;
  fullPageLabel?: string;
  howItStartedHeading?: string;
  documentsHeading?: string;
  personasHeading?: string;
  opportunitiesLabel?: string;
  barriersLabel?: string;
  enlargeLabel?: string;
  closeLabel?: string;
  previousLabel?: string;
  nextLabel?: string;
  pdfBadge?: string;
  pdfPageCounter?: string;
  pdfDownloadLabel?: string;
  fullscreenLabel?: string;
  exitFullscreenLabel?: string;
  creativeTitle?: string;
  creativeIntro?: string;
  portfolioSections?: {
    ux?: {
      title?: string;
      intro?: string;
    };
    brand?: {
      title?: string;
      intro?: string;
    };
    design?: {
      title?: string;
      intro?: string;
    };
    illustration?: {
      title?: string;
      intro?: string;
    };
  };
  portfolioViewAll?: string;
  creativeSections?: {
    data?: string;
    audit?: string;
    strategy?: string;
    designSystem?: string;
    ux?: string;
    brand?: string;
    illustration?: string;
    cover?: string;
    book?: string;
    campaign?: string;
    printAd?: string;
    graphic?: string;
    logo?: string;
  };
  kindLabels?: {
    data?: string;
    audit?: string;
    strategy?: string;
    designSystem?: string;
    ux?: string;
    brand?: string;
    logo?: string;
    campaign?: string;
    printAd?: string;
    graphic?: string;
    illustration?: string;
    cover?: string;
    book?: string;
  };
  uxCaseStudies: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    organization: string | null;
    role: string | null;
    years: string | null;
    skills: Array<string> | null;
    heroImage: ImageWithAlt | null;
    metrics: Array<
      {
        _key: string;
      } & Metric
    > | null;
  }> | null;
  portfolioUxCaseStudy: {
    _id: string;
    title: string;
    slug: string;
    summary: string;
    organization: string | null;
    role: string | null;
    years: string | null;
    skills: Array<string> | null;
    heroImage: ImageWithAlt | null;
    metrics: Array<
      {
        _key: string;
      } & Metric
    > | null;
  } | null;
  portfolioUxPieces: Array<{
    _id: string;
    title: string;
    slug: string;
    kind:
      | "audit"
      | "book"
      | "brand"
      | "campaign"
      | "cover"
      | "data"
      | "designSystem"
      | "graphic"
      | "illustration"
      | "logo"
      | "printAd"
      | "strategy"
      | "ux";
    image: ImageWithAlt | null;
    cardFit: "fill" | "whole" | null;
    opaque: boolean | null;
    gallery: Array<
      {
        _key: string;
      } & ImageWithAlt
    > | null;
    client: string | null;
    year: string | null;
    credit: string | null;
    summary: string | null;
    externalUrl: string | null;
    mature: boolean | null;
    featured: boolean | null;
    hasPage: boolean | true | null;
    caseStudySlug: string | null;
  }> | null;
  caseStudiesRowHeading?: string;
  caseStudyLabel?: string;
  matureLabel?: string;
  resumeTitle?: string;
  resumeIntro?: string;
  resumePdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  resumeDownloadLabel?: string;
  experienceHeading?: string;
  skillsHeading?: string;
  skillGroups?: Array<{
    heading: string;
    skills?: Array<string>;
    _type: "skillGroup";
    _key: string;
  }>;
  educationHeading?: string;
  education?: Array<string>;
  contactTitle?: string;
  contactIntro?: string;
  inquiryTypes?: Array<{
    label: string;
    description?: string;
    subject: string;
    _type: "inquiryType";
    _key: string;
  }>;
  resumePdfUrl: string | null;
  heroVideoUrl: string | null;
  headerLogoSize: {
    width: number;
    height: number;
  } | null;
  heroVideoType: string | null;
} | null;

// Source: src/lib/queries.ts
// Variable: CASE_STUDIES_QUERY
// Query: *[_type=="caseStudy" && defined(slug.current)]|order(order asc, title asc){_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics}
export type CASE_STUDIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  organization: string | null;
  role: string | null;
  years: string | null;
  skills: Array<string> | null;
  heroImage: ImageWithAlt | null;
  metrics: Array<
    {
      _key: string;
    } & Metric
  > | null;
}>;

// Source: src/lib/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type=="caseStudy" && slug.current==$slug][0]{  _id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics,body,links,seoDescription,heroBackground,personasIntro,  personas[]{_key,name,photo,traits,opportunitiesLead,opportunities,barriers,"photoSize": photo.asset->metadata.dimensions{width,height}},  galleries[]{_key,heading,intro,layout,placement,images[]{...,"size": asset->metadata.dimensions{width,height},"fullPageSize": fullPage.asset->metadata.dimensions{width,height}}}}
export type CASE_STUDY_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  organization: string | null;
  role: string | null;
  years: string | null;
  skills: Array<string> | null;
  heroImage: ImageWithAlt | null;
  metrics: Array<
    {
      _key: string;
    } & Metric
  > | null;
  body: RichText | null;
  links: Array<
    {
      _key: string;
    } & Link
  > | null;
  seoDescription: string | null;
  heroBackground: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  personasIntro: string | null;
  personas: Array<{
    _key: string;
    name: string;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    traits: Array<string> | null;
    opportunitiesLead: string | null;
    opportunities: Array<string> | null;
    barriers: Array<string> | null;
    photoSize: {
      width: number;
      height: number;
    } | null;
  }> | null;
  galleries: Array<{
    _key: string;
    heading: string;
    intro: string | null;
    layout: "phone" | "wide" | null;
    placement: "after" | "before" | null;
    images: Array<
      | {
          _key: string;
          _type: "galleryScreen";
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          fullPage?: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          };
          size: {
            width: number;
            height: number;
          } | null;
          fullPageSize: {
            width: number;
            height: number;
          } | null;
        }
      | {
          _key: string;
          _type: "imageWithAlt";
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          size: {
            width: number;
            height: number;
          } | null;
          fullPageSize: null;
        }
    > | null;
  }> | null;
} | null;

// Source: src/lib/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type=="caseStudy" && defined(slug.current)].slug.current
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/lib/queries.ts
// Variable: PORTFOLIO_SECTION_QUERY
// Query: *[_type=="creativeWork" && defined(slug.current) && kind in $kinds]|order(featured desc, order asc, title asc){_id,title,"slug":slug.current,kind,image,cardFit,"opaque": image.asset->metadata.isOpaque,gallery,client,year,credit,summary,externalUrl,mature,featured,  "hasPage": count(body) > 0 || count(documents) > 0,  "caseStudySlug": caseStudy->slug.current}
export type PORTFOLIO_SECTION_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  kind:
    | "audit"
    | "book"
    | "brand"
    | "campaign"
    | "cover"
    | "data"
    | "designSystem"
    | "graphic"
    | "illustration"
    | "logo"
    | "printAd"
    | "strategy"
    | "ux";
  image: ImageWithAlt | null;
  cardFit: "fill" | "whole" | null;
  opaque: boolean | null;
  gallery: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  client: string | null;
  year: string | null;
  credit: string | null;
  summary: string | null;
  externalUrl: string | null;
  mature: boolean | null;
  featured: boolean | null;
  hasPage: boolean | true | null;
  caseStudySlug: string | null;
}>;

// Source: src/lib/queries.ts
// Variable: PORTFOLIO_FEATURED_QUERY
// Query: *[_type=="creativeWork" && defined(slug.current) && featured == true && mature != true]|order(order asc, title asc){_id,title,"slug":slug.current,kind,image,cardFit,"opaque": image.asset->metadata.isOpaque,gallery,client,year,credit,summary,externalUrl,mature,featured,  "hasPage": count(body) > 0 || count(documents) > 0,  "caseStudySlug": caseStudy->slug.current}
export type PORTFOLIO_FEATURED_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  kind:
    | "audit"
    | "book"
    | "brand"
    | "campaign"
    | "cover"
    | "data"
    | "designSystem"
    | "graphic"
    | "illustration"
    | "logo"
    | "printAd"
    | "strategy"
    | "ux";
  image: ImageWithAlt | null;
  cardFit: "fill" | "whole" | null;
  opaque: boolean | null;
  gallery: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  client: string | null;
  year: string | null;
  credit: string | null;
  summary: string | null;
  externalUrl: string | null;
  mature: boolean | null;
  featured: boolean | null;
  hasPage: boolean | true | null;
  caseStudySlug: string | null;
}>;

// Source: src/lib/queries.ts
// Variable: CREATIVE_WORK_QUERY
// Query: *[_type=="creativeWork" && slug.current==$slug && kind in $kinds && mature != true][0]{  _id,title,"slug":slug.current,kind,image,client,year,credit,summary,gallery,howItStarted,body,documentsHeading,externalUrl,  documents[]{_key,title,"file": file.asset->{url,originalFilename},  pages[]{_key,asset,"size": asset->metadata.dimensions{width,height}}},  "caseStudy": caseStudy->{title,"slug":slug.current}}
export type CREATIVE_WORK_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  kind:
    | "audit"
    | "book"
    | "brand"
    | "campaign"
    | "cover"
    | "data"
    | "designSystem"
    | "graphic"
    | "illustration"
    | "logo"
    | "printAd"
    | "strategy"
    | "ux";
  image: ImageWithAlt | null;
  client: string | null;
  year: string | null;
  credit: string | null;
  summary: string | null;
  gallery: Array<
    {
      _key: string;
    } & ImageWithAlt
  > | null;
  howItStarted: RichText | null;
  body: RichText | null;
  documentsHeading: string | null;
  externalUrl: string | null;
  documents: Array<{
    _key: string;
    title: string;
    file: {
      url: string;
      originalFilename: string | null;
    } | null;
    pages: Array<{
      _key: string;
      asset: SanityImageAssetReference | null;
      size: {
        width: number;
        height: number;
      } | null;
    }>;
  }> | null;
  caseStudy: {
    title: string;
    slug: string;
  } | null;
} | null;

// Source: src/lib/queries.ts
// Variable: CREATIVE_WORK_PATHS_QUERY
// Query: *[_type=="creativeWork" && defined(slug.current) && (count(body) > 0 || count(documents) > 0) && mature != true]{kind,"slug":slug.current}
export type CREATIVE_WORK_PATHS_QUERY_RESULT = Array<{
  kind:
    | "audit"
    | "book"
    | "brand"
    | "campaign"
    | "cover"
    | "data"
    | "designSystem"
    | "graphic"
    | "illustration"
    | "logo"
    | "printAd"
    | "strategy"
    | "ux";
  slug: string;
}>;

// Source: src/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type=="page" && slug.current==$slug][0]{  _id,title,intro,image,body,cta,seoDescription}
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  intro: string | null;
  image: ImageWithAlt | null;
  body: RichText | null;
  cta: Link | null;
  seoDescription: string | null;
} | null;

// Source: src/lib/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type=="page" && defined(slug.current)].slug.current
export type PAGE_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/lib/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type=="experience"]|order(start desc){  _id,role,organization,start,end,location,highlights,  "caseStudies": caseStudies[defined(@->slug.current)]->{title,"slug":slug.current}}
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  role: string;
  organization: string;
  start: string;
  end: string | null;
  location: string | null;
  highlights: Array<string> | null;
  caseStudies: Array<{
    title: string;
    slug: string;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type=="siteSettings" && _id=="siteSettings"][0]{\n  ...,\n  "resumePdfUrl": resumePdf.asset->url,\n  "heroVideoUrl": heroVideo.asset->url,\n  "headerLogoSize": headerLogo.asset->metadata.dimensions{width,height},\n  "heroVideoType": heroVideo.asset->mimeType,\n  "featuredCaseStudies": featuredCaseStudies[defined(@->slug.current)]->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics},\n  "uxCaseStudies": uxCaseStudies[defined(@->slug.current)]->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics},\n  "caseStudyGroups": caseStudyGroups[]{_key,heading,"studies": studies[defined(@->slug.current)]->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics}},\n  "portfolioUxCaseStudy": portfolioUxCaseStudy->{_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics},\n  "portfolioUxPieces": portfolioUxPieces[defined(@->slug.current)]->{_id,title,"slug":slug.current,kind,image,cardFit,"opaque": image.asset->metadata.isOpaque,gallery,client,year,credit,summary,externalUrl,mature,featured,\n  "hasPage": count(body) > 0 || count(documents) > 0,\n  "caseStudySlug": caseStudy->slug.current}\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type=="caseStudy" && defined(slug.current)]|order(order asc, title asc){_id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics}': CASE_STUDIES_QUERY_RESULT;
    '*[_type=="caseStudy" && slug.current==$slug][0]{\n  _id,title,"slug":slug.current,summary,organization,role,years,skills,heroImage,metrics,body,links,seoDescription,heroBackground,personasIntro,\n  personas[]{_key,name,photo,traits,opportunitiesLead,opportunities,barriers,"photoSize": photo.asset->metadata.dimensions{width,height}},\n  galleries[]{_key,heading,intro,layout,placement,images[]{...,"size": asset->metadata.dimensions{width,height},"fullPageSize": fullPage.asset->metadata.dimensions{width,height}}}\n}': CASE_STUDY_QUERY_RESULT;
    '*[_type=="caseStudy" && defined(slug.current)].slug.current': CASE_STUDY_SLUGS_QUERY_RESULT;
    '*[_type=="creativeWork" && defined(slug.current) && kind in $kinds]|order(featured desc, order asc, title asc){_id,title,"slug":slug.current,kind,image,cardFit,"opaque": image.asset->metadata.isOpaque,gallery,client,year,credit,summary,externalUrl,mature,featured,\n  "hasPage": count(body) > 0 || count(documents) > 0,\n  "caseStudySlug": caseStudy->slug.current}': PORTFOLIO_SECTION_QUERY_RESULT;
    '*[_type=="creativeWork" && defined(slug.current) && featured == true && mature != true]|order(order asc, title asc){_id,title,"slug":slug.current,kind,image,cardFit,"opaque": image.asset->metadata.isOpaque,gallery,client,year,credit,summary,externalUrl,mature,featured,\n  "hasPage": count(body) > 0 || count(documents) > 0,\n  "caseStudySlug": caseStudy->slug.current}': PORTFOLIO_FEATURED_QUERY_RESULT;
    '*[_type=="creativeWork" && slug.current==$slug && kind in $kinds && mature != true][0]{\n  _id,title,"slug":slug.current,kind,image,client,year,credit,summary,gallery,howItStarted,body,documentsHeading,externalUrl,\n  documents[]{_key,title,"file": file.asset->{url,originalFilename},\n  pages[]{_key,asset,"size": asset->metadata.dimensions{width,height}}},\n  "caseStudy": caseStudy->{title,"slug":slug.current}\n}': CREATIVE_WORK_QUERY_RESULT;
    '*[_type=="creativeWork" && defined(slug.current) && (count(body) > 0 || count(documents) > 0) && mature != true]{kind,"slug":slug.current}': CREATIVE_WORK_PATHS_QUERY_RESULT;
    '*[_type=="page" && slug.current==$slug][0]{\n  _id,title,intro,image,body,cta,seoDescription\n}': PAGE_QUERY_RESULT;
    '*[_type=="page" && defined(slug.current)].slug.current': PAGE_SLUGS_QUERY_RESULT;
    '*[_type=="experience"]|order(start desc){\n  _id,role,organization,start,end,location,highlights,\n  "caseStudies": caseStudies[defined(@->slug.current)]->{title,"slug":slug.current}\n}': EXPERIENCE_QUERY_RESULT;
  }
}
